### ISSUE TITLE
Add support for JSS v10

### ISSUE THREAD

**Issue by oliviertassinari** [alitaheri/jss-rtl#6]
JSS is working on a v10 version. It's still in the alpha state. It would be great to prepare the support for this version. I doubt there is a lot to do. cc @kof.

![capture d ecran 2019-02-08 a 12 14 41](https://user-images.githubusercontent.com/3165635/52475200-227c2f80-2b9b-11e9-95e3-05f25ec9ee9b.png)

It has been working great so far with JSS v10-alpha on the Material-UI documentation.

**Comment by alitaheri** [comment]
@oliviertassinari Thanks for the heads up. I will investigate the breaking changes and update tests. there shouldn't be any changes. but in case an incompatible feature was added I should add tests and support for it.

**Comment by alitaheri** [comment]
All tests are passing with jss v10. and no relevant feature was introduced. I'll release my major with v10 as peer dependency after it's released.

**Comment by eps1lon** [comment]
Stable v10 was released yesterday: https://github.com/cssinjs/jss/releases/tag/v10.0.0

**Comment by alitaheri** [comment]
wow... nice 😍 

@eps1lon thanks for the heads up 👍

**Comment by alitaheri** [comment]
https://github.com/alitaheri/jss-rtl/releases/tag/v0.3.0
