### ISSUE TITLE
opt:in not working

### ISSUE THREAD

**Issue by pooriamo** [alitaheri/jss-rtl#7]
Hi

My webapp is fully RTL so I don't need to flip my styles, I just need mui's own components to flip. I'm using `jss.use(rtl({ opt: 'in' }));` as mentioned in docs. But that makes no difference and flipping persists.

**Comment by alitaheri** [comment]
can you show me more code? Something I can reproduce the issue with.

**Comment by pooriamo** [comment]
@alitaheri 
```
import React from 'react';
import { MuiThemeProvider } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
import JssProvider from 'react-jss/lib/JssProvider';
import { create } from 'jss';
import rtl from 'jss-rtl';
import { Provider } from 'react-redux'
import { jssPreset } from '@material-ui/core/styles';

// Configure JSS
const jss = create({ plugins: [...jssPreset().plugins] });
jss.use(rtl({ opt: 'out' }));

...


render() {
    return (
        <JssProvider
            jss={jss}
            registry={this.pageContext.sheetsRegistry}
            generateClassName={this.pageContext.generateClassName}
        >
            <MuiThemeProvider
                theme={this.pageContext.theme}
                sheetsManager={this.pageContext.sheetsManager}
            >
                <Component pageContext={this.pageContext} {...pageProps} />
            </MuiThemeProvider>
        </JssProvider>
    )
}
```

**Comment by alitaheri** [comment]
@pooriamo withStyles has it's own logic regarding `jss-rtl` this is related to material-ui.

https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/withStyles.js#L244

I don't know how it can be fixed, to be honest. but whatever the fix is, it's not related to this library. you need to open another issue (or PR) against material-ui
