### ISSUE TITLE
rtl not working 

### ISSUE THREAD

**Issue by soroushm** [alitaheri/jss-rtl#8]
Dear Ali,

Unfortunately, jss-rtl not working on material v4  take a look at this
<img width="1007" alt="Screen Shot 2019-06-01 at 9 11 08 AM" src="https://user-images.githubusercontent.com/1031663/58743784-78782a00-844d-11e9-8d95-41c64362e1a4.png">

on this case margin-left should be change to margin-right

[sample is here](https://codesandbox.io/s/material-demo-lfn0n)

**Comment by oliviertassinari** [comment]
Could you close the issue? It's unrelated to this package.

**Comment by soroushm** [comment]
@oliviertassinari so there is a plan to fix in material-ui packages? because just in v4 it broked
